version: '1.0'
services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice_shop
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    restart: unless-stopped
